
# 5 Interesting Numpy Array Functions


### Numpy is basically a module which has numerous types of functions mainly associated with arrays for other numerical concepts. In this notebook we are going to take a look on five numpy array functions. So lets's go

Write a short introduction about Numpy and list the chosen functions. 

- function 1
- function 2
- function 3
- function 4
- function 5


Let's begin by importing Numpy and listing out the functions covered in this notebook.

In [137]:
import numpy as np

In [1]:
#help(np)

In [2]:
#dir(np)

In [4]:
# List of functions explained 
#function1 = np.concatenate  # (change this)(trial)

function1 = np.stack
function2 = np.mean
function3 = np.sort
function4 = np.percentile
function5 = np.copyto

## Function 1 - np.stack

used to join sequence to an array along a new axis

In [3]:
#help(np.stack)

In [41]:
# Example 1 - working 
import numpy as np

array1 = [np.random.randn(3, 4) for _ in range(10)]
print(np.stack(array1, axis=0).shape)

array2 = [np.random.randn(3,4) for _ in range(10)]
print(np.stack(array2,axis=1).shape)



(10, 3, 4)
(3, 10, 4)


In [14]:
import numpy as np
array = [np.random.randn(3,2) for _ in range(3)]
np.stack(array,axis=2).shape

(3, 2, 3)

In [4]:
#help(np.random.randn())
dir(np.random.randn())

In [5]:
#dir(np.random)            #for np.random.randn

Explanation about example   -  first we need to import the numpy library,  from this library here i have used stack() . for creating an array follow this step
array =[ np.random.randn(2,5) for _ in range(4)]  likes this (4,2,5) this way we obtain an array
and to print the array we use (np.stack(array1, axis=0).shape)

In [42]:
# Example 2 - working
import numpy as np
a = np.array([2,3,4])
b = np.array([5,3,2])

print(np.stack((a,b)))

print("Changed axis stack     ", np.stack((a,b), axis=1))

[[2 3 4]
 [5 3 2]]
Changed axis stack      [[2 5]
 [3 3]
 [4 2]]


Explanation about example  - now here i have created to arrays directly without using random.randn() function but directly by np.array([ 3,5,3])  and stored into the variables a,b .  Now to stack those two array used np.stack((a,b)) we'll get an multidimensional array

In [51]:
# Example 3 - breaking (to illustrate when it breaks)
arr1 = [np.random.randn(7,4) for _ in range(6)]
print(np.stack(arr1, axis=-1).shape)

arr2 = [np.random.randn(9,4) for _ in range(8)]
#print(np.stack(arr2,axis=0).shape)

print(np.stack(arr2,axis=0))

(7, 4, 6)
[[[ 9.35410378e-01  2.42541130e-01  4.53838273e-01  3.72200876e-01]
  [-8.17880726e-01  1.32319622e-02 -2.59173142e-02 -1.27603031e+00]
  [ 5.35557980e-01 -3.52497106e-01 -5.64442542e-01 -9.71703440e-01]
  [-1.99848046e-01 -4.87302306e-01 -1.23759319e+00  1.38427902e+00]
  [-2.01671585e+00  6.83752686e-01  1.93271584e-01 -5.13776255e-01]
  [ 1.20937251e-01  2.28747240e-01  1.08714252e+00  1.51406922e+00]
  [ 1.02293510e+00  1.87173603e+00  3.42674607e+00 -1.75131983e-01]
  [-1.48494220e+00  1.28704041e+00 -3.48675088e-01  6.77894347e-01]
  [ 3.30407205e-01  1.63265317e+00 -2.07030897e+00  1.04064732e+00]]

 [[-8.69315525e-01  1.30073759e+00  9.94198847e-01  1.37791847e+00]
  [-7.43964478e-01 -2.61332146e-01 -6.67640962e-01 -3.16761585e-01]
  [ 3.36140396e-01  7.96180458e-01  1.66503882e+00  6.33700035e-01]
  [-1.86875438e+00  1.56156056e+00  2.98839363e-02  4.96722656e-01]
  [ 5.07204258e-01 -7.76341249e-01 -3.73022256e-01 -1.29562442e+00]
  [-5.95949103e-02 -3.23463298e-01 -

In [ ]:
#when we don't define a shape to a  array/stack  the representation of thw stack will be like the above example  

In [61]:
a = [np.random.randn(6,5) for _ in range(2)]
print(np.stack(a, axis=0).shape)
print(np.stack(a,axis=-1).shape)
print(np.stack(a,axis=2).shape)
print(np.stack(a, axis=3).shape)

(2, 6, 5)
(6, 5, 2)
(6, 5, 2)


AxisError: axis 3 is out of bounds for array of dimension 3

Explanation about example (why it breaks and how to fix it)

Some closing comments about when to use this function.

## Function 2 - np.concatenate

Add some explanations

In [62]:
# Example 1 - working
arr1 = [[1, 2], 
        [3, 4.]]

arr2 = [[5, 6, 7], 
        [8, 9, 10]]

np.concatenate((arr1, arr2), axis=1)

array([[ 1.,  2.,  5.,  6.,  7.],
       [ 3.,  4.,  8.,  9., 10.]])

Explanation about example

In [65]:
# Example 2 - working
arr1 = [[1, 2,4,5], 
        [3, 4,4,3]]

arr2 = [[5, 6, 7], 
        [8, 9, 10]]

np.concatenate((arr1,arr2),axis=1)

array([[ 1,  2,  4,  5,  5,  6,  7],
       [ 3,  4,  4,  3,  8,  9, 10]])

Explanation about example

In [63]:
# Example 3 - breaking (to illustrate when it breaks)
arr1 = [[1, 2], 
        [3, 4.]]

arr2 = [[5, 6, 7], 
        [8, 9, 10]]

np.concatenate((arr1, arr2), axis=0)

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 2 and the array at index 1 has size 3

Explanation about example (why it breaks and how to fix it)

Some closing comments about when to use this function.

## Function 3 - np.mean

np.mean()  function is used to find the mean of a numpy array


In [6]:
#dir(np.mean(3))

In [75]:
# Example 1 - working
arra1 = np.array([3,2,4])
arra2 = np.array([3,4,2])

print(np.mean(arra1))
print(np.mean(arr2))

3.0
7.5


Explanation about example

In [84]:
# Example 2 - working
arra3 = np.concatenate((arra1,arra2),axis=0)
print(np.mean(arra3))

3.0


Explanation about example  -  in first example i have simply created two individual array and got their mean by using np.mean() function to get the mean of the array/stack

In [86]:
# Example 3 - breaking (to illustrate when it breaks)
arra4 = np.array([2,3,4])
print(np.mean(arra4,arra3))          #only integer scalar arrays can be converted to a scalar index
                                                                 #it takes only one parameter

TypeError: only integer scalar arrays can be converted to a scalar index

Explanation about example (why it breaks and how to fix it)  -  to fix this TypeError we have to use only one parameter(array) should be given

Some closing comments about when to use this function.

## Function 4 - np.sort

np.sort() function is used to get a sorted array

In [7]:
#help(np.sort([2,3,4]))

In [90]:
# Example 1 - working
a = np.sort([7,8,5])
print(a)

[5 7 8]


Explanation about example

In [95]:
# Example 2 - working
b = ['guava', 'apple' , 'fig']
np.sort(b)

a1 = [2,9,2]
a2 = [8,4,6]

a3 =  np.concatenate((a1,a2),axis=0)
print(a3)
np.sort(a3)

[2 9 2 8 4 6]


array([2, 2, 4, 6, 8, 9])

Explanation about example

In [101]:
c = np.array([[4,3,5] , [8,7,9], [7,5,8]])
print(c)

np.sort(c)

[[4 3 5]
 [8 7 9]
 [7 5 8]]


array([[3, 4, 5],
       [7, 8, 9],
       [5, 7, 8]])

In [114]:
# Example 3 - breaking (to illustrate when it breaks)
d = np.array([6,3.3,4,8,"helloo",3])
print(d)
np.sort(d, axis=2, kind= 'quicksort')   #-1,0,1  can be used

['6' '3.3' '4' '8' 'helloo' '3']


AxisError: axis 2 is out of bounds for array of dimension 1

Explanation about example (why it breaks and how to fix it)  - given dimension of array is 1-D so axis should be bound to 1,0,-1

Some closing comments about when to use this function.

## Function 5 - np.percentile

np.percentile() function is used to find the percentile in a numpy array


In [117]:
# Example 1 - working
array = [2,55,6,3,9]
print(array)
print(np.percentile(array, 3))


[2, 55, 6, 3, 9]
2.12


Explanation about example

In [125]:
# Example 2 - working
a = np.array([5,3,7])
b = np.array([7,5,8])
c = np.concatenate([a,b])
print(c)
print(np.percentile(c,50))



d = np.array([[5,3,2],[4,3,5],[8,4,5]])
print(d)

print(np.percentile(d,4))

[5 3 7 7 5 8]
6.0
[[5 3 2]
 [4 3 5]
 [8 4 5]]
2.32


Explanation about example

In [127]:
# Example 3 - breaking (to illustrate when it breaks)
d = np.array([[5,3,2],[4,3,5],[8,4,5]])
print(d)

print(np.percentile(d,-2))

[[5 3 2]
 [4 3 5]
 [8 4 5]]


ValueError: Percentiles must be in the range [0, 100]

Explanation about example (why it breaks and how to fix it) -  percentile always range from [0,100] so negative range can't be given

Some closing comments about when to use this function.

## Function 6 - copyto

np.copyto - is used to copy the values of one array to another array

In [133]:
# Example 1 - working
import numpy as np
         
a = np.array([6,4,7])
a1 = np.array([3,2,7])
         
np.copyto(a1,a)
   
print(a1)
print(a)

[6 4 7]
[6 4 7]


Explanation about example

In [135]:
# Example 2 - working
b = np.array([[2,4,3],[5,4,2]])
b1 = np.array([[2,1,4],[5,3,6]])

np.copyto(b,b1)
print(b)

[[2 1 4]
 [5 3 6]]


Explanation about example

In [136]:
# Example 3 - breaking (to illustrate when it breaks)
c = np.array([4,3,5])
c1 = [3,2,5]

np.copyto(c1,c)    

TypeError: copyto() argument 1 must be numpy.ndarray, not list

Explanation about example (why it breaks and how to fix it)  --  arguments which are given to the copyto() needs to be arrays not list 

Some closing comments about when to use this function.

## Conclusion -                                                                                                                            Arrays are very frequently used in data science and NumPy aims to provide an array object and with the help of the object we can use the numpy functions on array

## Reference Links
Provide links to your references and other interesting articles about Numpy arrays:
* Numpy official tutorial : https://numpy.org/doc/stable/user/quickstart.html
* ...